#!/usr/bin/env bash

# source "$(dirname $0)/vars"

APP="$1"
CONTAINER_ID=$(docker ps -n 1 --no-trunc=true -q)
sudo su -c "echo '127.0.0.1 dev.ctmlabs.io' >> /var/lib/docker/containers/$CONTAINER_ID/hosts"
sudo su -c "cat /var/lib/docker/containers/$CONTAINER_ID/hosts > /tmp/hosts.txt"
